#!/bin/bash
# Script to add a user to Linux system
if [ $(id -u) -eq 0 ]; then
  egrep "^${1}" /etc/passwd >/dev/null
  if [ $? -eq 0 ]; then
    echo "${1} exists!"
    exit 1
  else
    pass=$(perl -e 'print crypt($ARGV[0], "password")' ${2})
    useradd -m -p $pass ${1}
    [ $? -eq 0 ] && echo "User has been added to system!" && mkdir -p /home/${1}/public || echo "Failed to add a user!"
  fi
else
  echo "Only root may add a user to the system"
  exit 2
fi
